export const GET_OTP_FOR_USERNAME_REQUEST = "GET_OTP_FOR_USERNAME_REQUEST";
export const GET_OTP_FOR_USERNAME_SUCCESS = "GET_OTP_FOR_USERNAME_SUCCESS";
export const GET_OTP_FOR_USERNAME_FAILURE = "GET_OTP_FOR_USERNAME_FAILURE";

export const RESEND_OTP_REQUEST = "RESEND_OTP_REQUEST";
export const RESEND_OTP_SUCCESS = "RESEND_OTP_SUCCESS";
export const RESEND_OTP_FAILURE = "RESEND_OTP_FAILURE";

export const VALIDATE_OTP_REQUEST = "VALIDATE_OTP_REQUEST";
export const VALIDATE_OTP_SUCCESS = "VALIDATE_OTP_SUCCESS";
export const VALIDATE_OTP_FAILURE = "VALIDATE_OTP_FAILURE";

export const RESET_ERROR = "RESET_ERROR";