export const GET_OTP_FOR_USERNAME_REQUEST = "GET_OTP_FOR_USERNAME_REQUEST";
export const GET_OTP_FOR_USERNAME_SUCCESS = "GET_OTP_FOR_USERNAME_SUCCESS";
export const GET_OTP_FOR_USERNAME_FAILURE = "GET_OTP_FOR_USERNAME_SUCCESS";

export const RESET_ERROR = "RESET_ERROR";

export const VALIDATE_OTP_REQUEST = "VALIDATE_OTP_REQUEST";
export const VALIDATE_OTP_SUCCESS = "VALIDATE_OTP_SUCCESS";
export const VALIDATE_OTP_FAILURE = "VALIDATE_OTP_FAILURE";